flags: {}
packages:
- '.'
extra-deps:
- HUnit-1.5.0.0
- hspec-2.4.0
- hspec-core-2.4.0
- hspec-expectations-0.8.2
- hspec-discover-2.4.0
- http-common-0.8.2.0
- http-streams-0.8.3.3
- readable-0.3.1
- test-framework-smallcheck-0.2
- openssl-streams-1.2.1.0
- digestive-functors-0.8.2.0
- snap-1.0.0.1
- snap-core-1.0.0.0
- heist-1.0.1.0
- map-syntax-0.2.0.1
- snap-server-1.0.2.2
- xmlhtml-0.2.3.5
- io-streams-1.3.5.0
- io-streams-haproxy-1.0.0.0
- clock-0.7.1
- errors-2.1.2
- unexceptionalio-0.3.0

resolver: lts-8.14
