flags: {}
packages:
- '.'
extra-deps:
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-expectations-0.7.2
- hspec-discover-2.2.0
- http-common-0.8.2.0
- http-streams-0.8.3.3
- readable-0.3.1
- test-framework-smallcheck-0.2
- openssl-streams-1.2.1.0
- digestive-functors-0.8.0.1
- snap-1.0.0.0
- snap-core-1.0.0.0
- heist-1.0.0.0
- map-syntax-0.2.0.1
- snap-server-1.0.0.0
- xmlhtml-0.2.3.5
- io-streams-1.3.5.0
- io-streams-haproxy-1.0.0.0
- clock-0.7.1
- errors-2.1.2

resolver: lts-2.17
