flags: {}
packages:
- '.'
extra-deps:
- aeson-1.1.2.0
- HUnit-1.6.0.0
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-expectations-0.8.2
- hspec-discover-2.4.4
- http-common-0.8.2.0
- http-streams-0.8.5.3
- readable-0.3.1
- test-framework-smallcheck-0.2
- openssl-streams-1.2.1.3
- digestive-functors-0.8.2.0
- snap-1.0.0.2
- snap-core-1.0.3.1
- heist-1.0.1.0
- map-syntax-0.2.0.2
- snap-server-1.0.3.1
- xmlhtml-0.2.5
- io-streams-1.5.0.1
- io-streams-haproxy-1.0.0.2
- clock-0.7.2
- errors-2.2.2
- unexceptionalio-0.3.0
- time-1.6.0.1

resolver: lts-8.14
